<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('siswas')->insert(
            [
                //Kelas1
                [
                    "nama_siswa" => "Muhammad Irfan Hakim",
                    "nis" => "3163285193",
                    "kelas" => "I",
                    "ttl" => "Cianjur, 29 September 2016",
                    "jenis_kelamin" => "L",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem Al-Husna RT/RW 005/001",
                    "nama_ayah" => "Wawan",
                    "nama_ibu" => "Rahmawati",
                    "pekerjaan_ayah" => "Buruh",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "1",
                ],
                [
                    "nama_siswa" => "Quthbi Hafy Sirojudin Al Birunni",
                    "nis" => "3167280726",
                    "kelas" => "I",
                    "ttl" => "Cianjur, 10 Agustus 2016",
                    "jenis_kelamin" => "L",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Haregem Al-Husna RT/RW 005/001",
                    "nama_ayah" => "Sirojudin",
                    "nama_ibu" => "Mia",
                    "pekerjaan_ayah" => "Wiraswasta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "1",
                ],
                [
                    "nama_siswa" => "Siti Nuraeni",
                    "nis" => "3164904203",
                    "kelas" => "I",
                    "ttl" => "Cianjur, 13 Juli 2016",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Poponcol RT/RW 005/001",
                    "nama_ayah" => "Irman",
                    "nama_ibu" => "Deuis",
                    "pekerjaan_ayah" => "Petani",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "1",
                ],

                //Kelas2
                [
                    "nama_siswa" => "Adeeva Shakila Faiha",
                    "nis" => "3161921685",
                    "kelas" => "II",
                    "ttl" => "Cianjur, 20 Juni 2016",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Haregem RT/RW 002/002",
                    "nama_ayah" => "Kodir",
                    "nama_ibu" => "Riska Risnawati",
                    "pekerjaan_ayah" => "Wiraswasta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "2",
                ],
                [
                    "nama_siswa" => "Putri Asani  Zahratunida",
                    "nis" => "3151206330",
                    "kelas" => "II",
                    "ttl" => "Cianjur, 16 Juli 2015",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "3",
                    "alamat" => "Kp. Galudra",
                    "nama_ayah" => "Ujang",
                    "nama_ibu" => "Ucu Lianti",
                    "pekerjaan_ayah" => "Buruh",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "2",
                ],
                [
                    "nama_siswa" => "Muhammad Aqil Sya'bana",
                    "nis" => "3150251218",
                    "kelas" => "II",
                    "ttl" => "Cianjur, 26 Mei 2016",
                    "jenis_kelamin" => "L",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 005/001",
                    "nama_ayah" => "Asep Suherman",
                    "nama_ibu" => "Devi",
                    "pekerjaan_ayah" => "Buruh",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "2",
                ],

                //Kelas3
                [
                    "nama_siswa" => "Mia Umiatul Gina",
                    "nis" => "0144111323",
                    "kelas" => "III",
                    "ttl" => "Cianjur, 27 Agustus 2014",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "TK Galudra Kencana",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Haregem RT/RW 005/001",
                    "nama_ayah" => "Moh.Andy Abdulah",
                    "nama_ibu" => "Juliana",
                    "pekerjaan_ayah" => "Karyawan Swasta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "3",
                ],
                [
                    "nama_siswa" => "Salsabila Putri Aswan",
                    "nis" => "212201030",
                    "kelas" => "III",
                    "ttl" => "Cianjur, 14 Maret 2014",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 001/002",
                    "nama_ayah" => "Iwan",
                    "nama_ibu" => "Ai Asri Nurhayati",
                    "pekerjaan_ayah" => "Petani",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "3",
                ],
                [
                    "nama_siswa" => "Kaipa Tiljalah",
                    "nis" => "222302049",
                    "kelas" => "III",
                    "ttl" => "Cianjur, 29 Februari 2014",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 005/001",
                    "nama_ayah" => "Asep Suherman",
                    "nama_ibu" => "Devi",
                    "pekerjaan_ayah" => "Buruh",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "3",
                ],

                //Kelas4
                [
                    "nama_siswa" => "Syifa Fitri Agustini",
                    "nis" => "0139604544",
                    "kelas" => "IV",
                    "ttl" => "Cianjur, 20 Agustus 2013",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 002/002",
                    "nama_ayah" => "Rusli Efendi",
                    "nama_ibu" => "Yulianti",
                    "pekerjaan_ayah" => "Swasta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "4",
                ],
                [
                    "nama_siswa" => "Aqila Putri",
                    "nis" => "0202101002",
                    "kelas" => "IV",
                    "ttl" => "Cianjur, 25 Agustus 2013",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "3",
                    "alamat" => "Kp. Haregem RT/RW 002/002",
                    "nama_ayah" => "Cece Puad",
                    "nama_ibu" => "Elin Herlina",
                    "pekerjaan_ayah" => "Swasta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "4",
                ],
                [
                    "nama_siswa" => "Siska Ramadani Putri",
                    "nis" => "01373121028",
                    "kelas" => "IV",
                    "ttl" => "Cianjur, 28 Juli 2013",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 003/002",
                    "nama_ayah" => "Djalaludin",
                    "nama_ibu" => "Bariah",
                    "pekerjaan_ayah" => "Wirausaha",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "4",
                ],

                //Kelas5
                [
                    "nama_siswa" => "Siti Rahmah Nuranjani",
                    "nis" => "192001050 ",
                    "kelas" => "V",
                    "ttl" => "Cianjur, 28 Juli 2012",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 003/002",
                    "nama_ayah" => "Djalaludin",
                    "nama_ibu" => "Bariah",
                    "pekerjaan_ayah" => "Wirausaha",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "5",
                ],
                [
                    "nama_siswa" => "Dela Sukma Alisa",
                    "nis" => "192001008 ",
                    "kelas" => "V",
                    "ttl" => "Cianjur, 3 Oktober 2012",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Haregem RT/RW 005/002",
                    "nama_ayah" => "Yusuf",
                    "nama_ibu" => "-",
                    "pekerjaan_ayah" => "Wirausaha",
                    "pekerjaan_ibu" => "-",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "5",
                ],
                [
                    "nama_siswa" => "Maya Chyani",
                    "nis" => "192001024 ",
                    "kelas" => "V",
                    "ttl" => "Cianjur, 05 Agustus 2012",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 003/002",
                    "nama_ayah" => "Nurhidayat",
                    "nama_ibu" => "Lilis Sumyati",
                    "pekerjaan_ayah" => "Wirausaha",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "5",
                ],

                //Kelas6
                [
                    "nama_siswa" => "Iis Siti Salmah",
                    "nis" => "0129368275",
                    "kelas" => "VI",
                    "ttl" => "Cianjur, 04 September 2011",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Haregem RT/RW 003/002",
                    "nama_ayah" => "Hasannudin",
                    "nama_ibu" => "Siti Rohimah",
                    "pekerjaan_ayah" => "Wiraswsta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "6",
                ],
                [
                    "nama_siswa" => "Sakila",
                    "nis" => "0124276827",
                    "kelas" => "VI",
                    "ttl" => "Cianjur, 09 Januari 2012",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "PAUD Galudra Kencana",
                    "jmlh_sodara" => "1",
                    "alamat" => "Kp. Haregem RT/RW 005/001",
                    "nama_ayah" => "Asep Sopandi",
                    "nama_ibu" => "Ayu Naila",
                    "pekerjaan_ayah" => "Wiraswsta",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "6",
                ],
                [
                    "nama_siswa" => "Selpi Asanti",
                    "nis" => "0117183274",
                    "kelas" => "VI",
                    "ttl" => "Cianjur, 06 April 2011",
                    "jenis_kelamin" => "P",
                    "agama" => "Islam",
                    "pendik_sebelumnya" => "-",
                    "jmlh_sodara" => "2",
                    "alamat" => "Kp. Haregem RT/RW 005/001",
                    "nama_ayah" => "Adang",
                    "nama_ibu" => "Ai Nuraeni",
                    "pekerjaan_ayah" => "Buruh",
                    "pekerjaan_ibu" => "IRT",
                    "wali_siswa" => "-",
                    "tahun_pelajaran" => "2024",
                    "id_wali_kelas" => "6",
                ],
            ]
        );
    }
}
